# Generated by Django 4.0.5 on 2022-06-25 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date_joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last_login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('email', models.EmailField(db_index=True, max_length=60, unique=True, verbose_name='email')),
                ('type', models.CharField(choices=[('STUDENT', 'STUDENT'), ('TUTOR', 'TUTOR'), ('ADMIN', 'ADMIN')], max_length=7)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
