# Generated by Django 4.0.5 on 2022-06-25 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_payment_history'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment_History',
            new_name='PaymentHistory',
        ),
    ]
