# Generated by Django 4.0.5 on 2022-06-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_payment_history_paymenthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='amount',
            field=models.FloatField(max_length=6),
        ),
    ]
