# Generated by Django 4.0.5 on 2022-06-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_paymenthistory_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
